name: Python CI

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies

      - name: Install curl
        run: sudo apt-get install curl  # Install curl

      - name: Send GET Request to Flask App
        run: |
          response=$(curl http://localhost:5000)  # Adjust the URL as needed
          echo "Response from Flask App: $response"

      - name: Display Response
        run: |
          echo "Response from Flask App: $response"
